name: lpchub
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  firebase_core: ^0.5.0+1
  google_sign_in: ^4.5.4
  flutter_facebook_login: ^3.0.0
  http: ^0.12.2
  font_awesome_flutter: ^8.10.0
  advance_pdf_viewer: ^1.2.2
  google_fonts: ^1.1.0
  share: ^0.6.5+2
  url_launcher: ^5.7.2
  provider: ^4.3.2+2
  lottie: ^1.0.1
  flutter_spinkit:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/landing.jpg
    - asset/images/img1.png
    - asset/images/img2.png
    - asset/images/classroom.png
    - asset/images/cms.png
    - asset/images/info.png
    - asset/images/info1.png
    - asset/images/info2.png
    - asset/images/info3.png
    - asset/images/landing.png
    - asset/images/lpc.png
    - asset/images/demo.png
    - asset/bunkzone.json
    - asset/chatting.json
    - asset/check.json
    - asset/dailynews.json
    - asset/human.json
    - asset/mentor.json
    - asset/plane.json
    - asset/resource.json
    - asset/schoolhub.json
    - asset/schoolhub1.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MeriendaOne
      fonts:
        - asset: asset/fonts/MeriendaOne-Regular.ttf

    - family: Caveat
      fonts:
        - asset: asset/fonts/Caveat-Regular.ttf

    - family: Lobster
      fonts:
        - asset: asset/fonts/Lobster-Regular.ttf

    - family: Sora
      fonts:
        - asset: asset/fonts/Sora.ttf

    - family: Roboto
      fonts:
        - asset: asset/fonts/RobotoSlab-VariableFont_wght.ttf

    - family: Pacifico
      fonts:
        - asset: asset/fonts/Pacifico-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
